/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.component;

/**
 *
 * @author MTMQ
 */
public class Item_People extends javax.swing.JPanel {

    /**
     * Creates new form Item_People
     */
    public Item_People() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageAvatar1 = new com.raven.swing.ImageAvatar();
        imageAvatar2 = new com.raven.swing.ImageAvatar();
        imageAvatar3 = new com.raven.swing.ImageAvatar();
        imageAvatar4 = new com.raven.swing.ImageAvatar();
        imageAvatar5 = new com.raven.swing.ImageAvatar();
        imageAvatar6 = new com.raven.swing.ImageAvatar();
        imageAvatar7 = new com.raven.swing.ImageAvatar();
        imageAvatar8 = new com.raven.swing.ImageAvatar();
        imageAvatar9 = new com.raven.swing.ImageAvatar();
        imageAvatar10 = new com.raven.swing.ImageAvatar();
        imageAvatar11 = new com.raven.swing.ImageAvatar();

        setBackground(new java.awt.Color(229, 229, 229));

        imageAvatar11.setBorderSize(1);
        imageAvatar11.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/profile.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imageAvatar11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 333, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imageAvatar11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.ImageAvatar imageAvatar1;
    private com.raven.swing.ImageAvatar imageAvatar10;
    private com.raven.swing.ImageAvatar imageAvatar11;
    private com.raven.swing.ImageAvatar imageAvatar2;
    private com.raven.swing.ImageAvatar imageAvatar3;
    private com.raven.swing.ImageAvatar imageAvatar4;
    private com.raven.swing.ImageAvatar imageAvatar5;
    private com.raven.swing.ImageAvatar imageAvatar6;
    private com.raven.swing.ImageAvatar imageAvatar7;
    private com.raven.swing.ImageAvatar imageAvatar8;
    private com.raven.swing.ImageAvatar imageAvatar9;
    // End of variables declaration//GEN-END:variables
}
